### ISSUE TITLE
General, request for new animation 

### ISSUE THREAD

**Issue by saboorazizi** [IanLunn/Hover#103]
Thanks from your great animations library. I saw an animation in https://www.style-instruct.com/
while hover pointer over an image the image corners move up with shadow. Can you tell me how to have this animation? Do you plan to add this animation in your library or not?

Thanks

**Comment by IanLunn** [comment]
Cool animation. I don't intend to add it but would be happy for anyone else to contribute this effect. Note however that we couldn't do the full effect because cursor interaction would require the use of JavaScript and Hover.css is a CSS library only.
