### ISSUE TITLE
effect takes place only over text

### ISSUE THREAD

**Issue by KuRLZ** [IanLunn/Hover#104]
I may be coding this incorrectly, but when I hover over my link that has the "sweep left" effect applied to it, the only part that's effected by the hovering is the actual text and not the entire Div.
How would I correct this?

Couldn't get it to upload for some reason. Maybe because there is a gif in it.
Here is the website:

www.superfarmerbros.com

It's the red bar on the side column that says "SuperFarmerBros"

**Comment by IanLunn** [comment]
Looks like it is working now. Closing issue but if still a problem please let me know which browser you are experiencing this in.

**Comment by KuRLZ** [comment]
thanks
