### ISSUE TITLE
StylusCSS Suport

### ISSUE THREAD

**Issue by felipesousa** [IanLunn/Hover#105]
Hello Brother, I am thinking about your project and Stylus CSS, you are going add Support?

**Comment by IanLunn** [comment]
No, sorry. It takes too much time to maintain.

**Comment by felipesousa** [comment]
if you like, I can help you, what think?

**Comment by IanLunn** [comment]
Thanks for the offer but it means each future update will also have to be done in Stylus. I already plan to drop LESS support because Sass and LESS is too much.

If anyone else is interested in Stylus support, I'm sure they'd appreciate a forked port.

**Comment by felipesousa** [comment]
ok @IanLunn thanks for response, your project is awesome!
