### ISSUE TITLE
Feature request: special slider animation

### ISSUE THREAD

**Issue by SumNeuron** [IanLunn/Hover#108]
Hey Ian,
This is really awesome 👍 
I was curious if you could make a special animation for fa-sliders (\f1de). This involves a bit more manipulation of the icon, as I would like the knobs to move left and right.
Do you think that is possible?
Thanks!

addendum: is it possible to have different icons for the same effect in for different instances?

**Comment by IanLunn** [comment]
Too scenario specific to implement, sorry. You can change the icon for different effects.
