### ISSUE TITLE
Hover effect not working

### ISSUE THREAD

**Issue by PAMulligan** [IanLunn/Hover#111]
I'm creating a Rails app, and I've put all the scss files into my vendor folder, including the effects folder. Everything loads just fine, but nothing happens on hover with shadow-radial. Here's how my html looks:

    <div class="hvr-shadow-radial image-tag-container container">
        <div class="row">
	    <div class="col-xs-12 col-md-6 col-lg-4">
	        <%= link_to image_tag("volunteer.png"), new_volunteer_path %>
	    </div>
	</div>
    </div>

The click effect triggers the shadow-radial, but not hover. Any thoughts on what I'm doing wrong?

EDIT

This is actually only true when I'm using Chrome Dev tools and inspecting the page as a mobile device. I still don't understand why, but important to note that it works in fullscreen.

**Comment by IanLunn** [comment]
Chrome Dev tools is emulating a mobile device that doesn't have the ability to hover, hence the effect not working in that context.
