### ISSUE TITLE
Show icons before the text? 

### ISSUE THREAD

**Issue by pkiula** [IanLunn/Hover#113]
I've been trying to change the ":after" to ":before". Doesn't seem to show the icon on the left? Any help welcome. Say, for the hvr-icon-float. Could you please guide me on how I should change the CSS? Thank you!

**Comment by IanLunn** [comment]
Change:

```
.hvr-icon-float::before {
  right: 1em;
}
```

to:

```
.hvr-icon-float::before {
  left: 1em;
}
```

Change:

```
.hvr-icon-float {
  padding-right: 2.2em;
}
```

To:

```
.hvr-icon-float {
  padding-left: 2.2em;
}
```
