### ISSUE TITLE
fix deprecation warning in mixin

### ISSUE THREAD

**Issue by HongPong** [IanLunn/Hover#115]
I got the sass compiler to quit freaking out at me by wrapping the unquote parameters in #{} .

```sass
@mixin prefixed($property, $value) {
  -webkit-#{$property}: unquote(#{$value});
  #{$property}: unquote(#{$value});
}
```
Errors similar to:
```
DEPRECATION WARNING: Passing 0.3s, a non-string value, to unquote()
will be an error in future versions of Sass.
DEPRECATION WARNING: Passing perspective(1px) translateZ(0), a non-string value, to unquote()
will be an error in future versions of Sass.
```

**Comment by IanLunn** [comment]
What version of Hover.css and Sass are you using please? Latest version of Hover.css doesn't use `unquote()`.

**Comment by HongPong** [comment]
Ah, I'll close the ticket. This was a little while back - I believe it was in a child theme of this project https://www.drupal.org/project/zurb_foundation 
Which at the time was probably on Foundation 6.2.x and the packages it installed.  I thought I had the most recent version of this at the time, but perhaps not!
