### ISSUE TITLE
change width and make it center

### ISSUE THREAD

**Issue by abdhannan** [IanLunn/Hover#124]
How to change width the effect for ex: 20% of a parent element and make it center?

Thank you!

**Comment by arximughal** [comment]
@abdhannan Please explain it a little bit more, or better share a screenshot/reference of what you need.

**Comment by IanLunn** [comment]
@abdhannan You might want to try something like this:

```
display: block;
width: 20%;
margin-left: auto;
margin-right: auto;
```
