### ISSUE TITLE
FontAwesome 5 Compatibility

### ISSUE THREAD

**Issue by reubenbrown** [IanLunn/Hover#129]
Font Awesome has upgraded to [version 5.0.6](https://fontawesome.com/how-to-use/upgrading-from-4) which has many breaking changes from the previous versions. 

One of the biggest changes is they switched the font-family name `FontAwesome` to `Font Awesome 5 Free` or `Font Awesome 5 Pro`. This appears to be the main reason the hover library doesn't work with the latest version of FontAwesome. 

Switching those values in the hover css/sass/less files should resolve the issue, but then this library wouldn't work for users using hover and FontAwesome 4.x. 

Are there any plans to upgrade this library to be compatible with both versions (4 & 5) of FontAwesome?

**Comment by IanLunn** [comment]
We'll decouple from FontAwesome in a future version so more choice is available. See this ticket: https://github.com/IanLunn/Hover/issues/59
