### ISSUE TITLE
How to get background effects on rounded elements?

### ISSUE THREAD

**Issue by pkiula** [IanLunn/Hover#149]
Hello. Love this script, but would love to make this work with icons in circles. Here's my CodePen: https://codepen.io/pkiula/pen/gNYLYO

The background fill with `hvr-bounce-to-right` is forcing itself to be blue and square. How could I control the color and the roundedness? Thanks!

**Comment by IanLunn** [comment]
Set `overflow: hidden` on the element it's being applied to then change the styles via the `:before` pseudo-element: https://codepen.io/IanLunn/pen/xxKvYxe
