### ISSUE TITLE
problem with addMediaConversion 

### ISSUE THREAD

**Issue by Adamkaram** [IanLunn/Hover#150]
when i want to resize an image and use this method addMediaConversion i got this error :
_________________________________________________________________________________________________
SQLSTATE[HY000]: General error: 1 no such table: jobs (SQL: insert into "jobs" ("queue", "attempts", "reserved_at", "available_at", "created_at", "payload") values (default, 0, ?, 1562695873, 1562695873, {"displayName":"Spatie\\MediaLibrary\\Jobs\\PerformConversions","job":"Illuminate\\Queue\\CallQueuedHandler@call","maxTries":null,"delay":null,"timeout":null,"timeoutAt":null,"data":{"commandName":"Spatie\\MediaLibrary\\Jobs\\PerformConversions","command":"O:43:\"Spatie\\MediaLibrary\\Jobs\\PerformConversions\":9:{s:14:\"\u0000*\u0000conversions\";O:51:\"Spatie\\MediaLibrary\\Conversion\\ConversionCollection\":2:{s:8:\"\u0000*\u0000media\";N;s:8:\"\u0000*\u0000items\";a:1:{i:0;O:41:\"Spatie\\MediaLibrary\\Conversion\\Conversion\":7:{s:7:\"\u0000*\u0000name\";s:5:\"thumb\";s:28:\"\u0000*\u0000extractVideoFrameAtSecond\";i:0;s:16:\"\u0000*\u0000manipulations\";O:26:\"Spatie\\Image\\Manipulations\":1:{s:23:\"\u0000*\u0000manipulationSequence\";O:33:\"Spatie\\Image\\ManipulationSequence\":1:{s:9:\"\u0000*\u0000groups\";a:1:{i:0;a:4:{s:8:\"optimize\";s:341:\"{\"Spatie\\\\ImageOptimizer\\\\Optimizers\\\\Jpegoptim\":[\"--strip-all\",\"--all-progressive\"],\"Spatie\\\\ImageOptimizer\\\\Optimizers\\\\Pngquant\":[\"--

________________________________________________________

as i now this problem Because of a table in data base named jobs but should i create one or there is another something related to this problem?

**Comment by ahmed-aliraqi** [comment]
@Adamkaram you should run `queue:table` and `migrate` command  to add jobs table 
```
php artisan queue:table && php artisan migrate
```

**Comment by Adamkaram** [comment]
thanks a buch
but i can't see any different in image's size 
i used this method for conv 

public function registerMediaConversions(?Media $Media = null)

    {

        $this->addMediaConversion('thumb')
        ->height(20)
        ->width(20);
    } 
and there is no folder for convension or something like thta

**Comment by ahmed-aliraqi** [comment]
I did not use this package but I told you to solve the problem that appeared to you

**Comment by ahmed-aliraqi** [comment]
I use [Laravel Media Library](https://docs.spatie.be/laravel-medialibrary/v7/converting-images/defining-conversions/) to resize images

**Comment by Adamkaram** [comment]
ok i'll see about it
