### ISSUE TITLE
Add flip effects

### ISSUE THREAD

**Issue by c-das** [IanLunn/Hover#41]
So I was going through [this post](http://davidwalsh.name/css-flip) on David Walsh's blog, about horizontal and vertical flip effects in CSS3 and thought it'd make for a nice addition to this library. I can take this over the coming weekend.

Let me know what you think!

**Comment by IanLunn** [comment]
Hi, sounds cool. Note that effects should consist of one HTML element only, so whatever appears on the back would need to be controlled via CSS (you'd probably require a psuedo-element).

Here's some [guidelines for submitting effects](https://github.com/IanLunn/Hover/blob/master/CONTRIBUTING.md). Good luck!

**Comment by IanLunn** [comment]
Will close this as it's not actually an issue but feel free to get in touch again if you need help.
