### ISSUE TITLE
Border CSS elements on mobile - Small screens

### ISSUE THREAD

**Issue by thenexus00** [IanLunn/Hover#49]
For the Border effects, Something I have dealt with but is an issue..

When you have a hvr-outline-in for example on an image/link and your on say bootstrap and scale down or on mobile you get a little horizontal scroll because of the CSS this adds in.

**Comment by IanLunn** [comment]
I don't think this requires a fix as an element overflowing its parent is expected browser behaviour. If it is an issue in your specific situation, the parent element should be given the appropriate `overflow` property. This can either be set on the element itself, for example:

```
.hvr-outline-out {
  overflow: hidden;
}
```

Or alternatively on your own parent element.
