### ISSUE TITLE
Blurry text inside "hvr-grow" element if positioned with fixed property (Safari OS X 10.10.2)

### ISSUE THREAD

**Issue by udu5syjt1syj5s51t6y** [IanLunn/Hover#58]
Using hvr-grow class with button tag or also <a>, the text inside the element will massively blur on scaling if the element is fixed positioned (Safari OS X 10.10.2).
![s](https://cloud.githubusercontent.com/assets/5564178/6431181/d07aea42-c027-11e4-832c-217d0268f8dc.png)
![s2](https://cloud.githubusercontent.com/assets/5564178/6431182/d0a1a902-c027-11e4-8a64-a58caed65ce3.png)

**Comment by l0010o0001l** [comment]
I second this ^

**Comment by IanLunn** [comment]
I don't think this is directly fixable in Hover.css but a workaround is to wrap the element in another and place the Hover class on the parent element, like so:

```html
<div class="hvr-grow">
    <a href="#">Grow</a>
</div>
```
