### ISSUE TITLE
Decouple FontAwesome?

### ISSUE THREAD

**Issue by moneytree-doug** [IanLunn/Hover#59]
I have my own web font, and it would be really awesome if I can just throw these classes on to my existing icons and have the effects added to it.

**Comment by kvnxdev** [comment]
I had the same problem like you so I decided to fork and edit it. Maybe this version is interesting for you:
Fork: https://github.com/kvnxdev/Hover
How To: https://github.com/kvnxdev/Hover#using-fontawesome-with-icon-effects

**Comment by moneytree-doug** [comment]
@kvnxdev Thanks for the comment, I'll check it out!

**Comment by gregoryagu** [comment]
@kvnxdev Can you explain how your fork can be used with Google Material icons?  I looked at the link in you posted, but it appears to be the same readme as the original.  I didn't see anything about using a different font.

**Comment by IanLunn** [comment]
You can now do this in v2.3.0 by putting `hvr-icon` on your icon and the effect you want on the parent element. Example:

```
<a href="#" class="hvr-icon-spin">
  Icon Spin
  <img src="myicon.svg" class="hvr-icon" />
</a>
```

**Comment by gregoryagu** [comment]
That's HoverAwesome!
