### ISSUE TITLE
hvr-grow hover.

### ISSUE THREAD

**Issue by Copser** [IanLunn/Hover#62]
Hello, I have a question about this element, more precise about aligning. I have a series of elements who are forming a circle in mine div, this is the example http://dabblet.com/gist/3864650.
I want to use grow hover on all buttons, and I have done all the tutorial said, been using hover-min.css, but when I use it, the property align all icons in the middle, I have tried and put 'vertical-align:none' but that did not do the trick.
How can I over come this.
Tank you.

**Comment by IanLunn** [comment]
Hi @Copser, the initial value for `vertical-align` is `baseline` so you may want to try that. You may be better using `display: block` too.

If this doesn't work, please provide a link that includes the Hover effects and I can debug.

**Comment by Copser** [comment]
Tank you Ian, I will do that as soon as possible.

**Comment by Copser** [comment]
Hello @IanLunn I have tried to alter the css code like you said but it does not work. This is a link to your https://github.com/IanLunn/Hover/blob/master/css/hover.css repository, if I understand you well you want me to provide you link to the hover effect I want to use. 
In this case I will use only the first effect in your css file, .hvr-grow effect.

**Comment by IanLunn** [comment]
Please provide a link to your project that includes the broken version that you described in your first post.
