### ISSUE TITLE
Replicating the styling to a button

### ISSUE THREAD

**Issue by iamDevlin** [IanLunn/Hover#65]
![btn](https://cloud.githubusercontent.com/assets/12197992/7999742/a17fcd46-0b83-11e5-9fce-18089b240c35.png)
My button looks weird. The css is:

.login-btn{    
    margin: .4em;
    padding: 1em;
    cursor: pointer;
    background: #e1e1e1;
    text-decoration: none;
    color: #666;
    -webkit-tap-highlight-color: rgba(0,0,0,0);
}

**Comment by iamDevlin** [comment]
.login-btn{    
    background-color:#e1e1e1;
    border:0px solid #e1e1e1;
    display:inline-block;
    cursor:pointer;
    color:#666;
    font-family:Arial;
    font-size:14px;
    padding:15px 28px;
    text-decoration:none;
}

**Comment by mufasser** [comment]
.login-btn{

background-color:#e1e1e1;
border:0px solid #e1e1e1;
display:inline-block;
cursor:pointer;
color:#666;
font-family:Arial;
font-size:14px;
padding:15px 28px;
text-decoration:none;
}

in this css code

if you set 0px to border when y are you adding
*solid and color*if it is ZERO then just apply *border:0px; *
 now your code look like


.login-btn{

background-color:#e1e1e1;
border:0px; /* border:none */
display:inline-block;
cursor:pointer;
color:#666;
font-family:Arial;
font-size:14px;
padding:15px 28px;
text-decoration:none;
}




On Fri, Jun 5, 2015 at 10:19 AM, iamDevlin <notifications@github.com> wrote:

> .login-btn{
>
> background-color:#e1e1e1;
> border:0px solid #e1e1e1;
> display:inline-block;
> cursor:pointer;
> color:#666;
> font-family:Arial;
> font-size:14px;
> padding:15px 28px;
> text-decoration:none;
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IanLunn/Hover/issues/65#issuecomment-109166547>.
>



-- 


*If you have any queries; or require any assistance, please do not hesitate
to contact us. Thank you. Regards*
*Mufasser Islam​*
C.E.O. of Webica Soft <http://webicasoft.com>
IT and Designing Services
+92-323-4062533

Facebook <https://www.facebook.com/mufasseri> | *Call on Skype​:* mufasser
