### ISSUE TITLE
Any way of getting IE8 to fallback nicely to simple hover?

### ISSUE THREAD

**Issue by sicollins** [IanLunn/Hover#72]
I'm using bootstrap 3 and your nice background transitions like bounce-to-right.

However no matter what I try I cannot get simple hover (bg color change) working in IE8. In IE8 the button is rendered in non-hover state with the darker hover color I've set up.

Has anyone had similar issue and found a work around?

**Comment by IanLunn** [comment]
bounce-to-right uses a CSS pseudo-element for the moving element when a button is hovered over. IE8 doesn't support pseudo-elements.

To work around this and provide a fallback for IE8, you could use [conditional comments](http://www.quirksmode.org/css/condcom.html) to load styles specific for browsers below IE9.

**Comment by sicollins** [comment]
Thanks for reply - yes I've tried using conditional comments.

in IE8 my html tag for exmaple looks like <html class="ie8">

Then I have the following:

.ie8 a.btn-primary.hvr-bounce-to-right {
    background: $primary-color !important;
	&:hover,
	&:focus,
	&:active {
		background: $primary-color-hover !important;		
	}
}

But just doesn't work. I know IE8 can struggle with :hover but not on a simple <a>

I know the selector works because I can set color: yellow for example on the hover and that does work.

**Comment by IanLunn** [comment]
Can you provide a link?
