### ISSUE TITLE
generator

### ISSUE THREAD

**Issue by fnnzzz** [IanLunn/Hover#82]
I think that to make a CSS generator, where you can select only the desired animation would be a good idea. Often, you need only a few animations of the entire list, and pull out all the CSS for this is somehow not good.

I could help you in this.

**Comment by IanLunn** [comment]
This isn't something I'd want to take on but I like the idea. If you can do it, I'd be glad to provide feedback.

**Comment by IanLunn** [comment]
I suspect it is different to how you are planning but in the future I will be converting Hover.css to use Sass @imports for custom builds. If you are going to build a web-based generator, maybe it could leverage that.

**Comment by finn1nets** [comment]
Yes, I was referring to the web generator, like bootstrap. But imports also a good idea, I think!

How can I help you?
