### ISSUE TITLE
Change bg color

### ISSUE THREAD

**Issue by tmrdurgun** [IanLunn/Hover#90]
How to change bg color for a specific element when using hover bg transition class ?

**Comment by SabeehJaved** [comment]
Workaround For chrome.
Inspect the element using ctrl+shift+I
click " :hov " to expose the hover class
from there you can change the background color in hover.css file.

**Comment by IanLunn** [comment]
Thanks for the tip @SabeehJaved.

A lot of the background transitions use a pseudo-element to act as the background. To change the background of the Sweep To Right effect for example, you'd use this:

```
.hvr-sweep-to-right::before {
    background-color: red;
}
```
