### ISSUE TITLE
Edge Browser crashing

### ISSUE THREAD

**Issue by djpease** [IanLunn/Hover#91]
I attempted to add the hvr-sweep-to-right to a site, but it currently crashes the IE edge browser. 

The demo site here also crashes on IE.
http://ianlunn.github.io/Hover/

Using version 25.10586.0.0 on windows 10.
![2016-04-28 15_59_06-start](https://cloud.githubusercontent.com/assets/11236203/14901253/279adf3c-0d5a-11e6-8c0e-eb38bcfed23d.png)

This is what you see when you load the site:

![2016-04-28 15_54_30-start](https://cloud.githubusercontent.com/assets/11236203/14901148/9d4278d6-0d59-11e6-99db-d26eb53f8b66.png)

IE 11 does not crash but there is a lot of "blinking" of the elements as you hover over them in some areas.

**Comment by IanLunn** [comment]
Anyone else having this issue/able to test? Not seeing it myself using same version.

@djpease Are you able to test in a new InPrivate window to be sure it's not an add-on causing the issue?

**Comment by djpease** [comment]
Hi it is possible it was limited to one computer. I cannot reproduce after trying other computers. Edge is up to date but seems corrupted somehow. This can likely be closed, thanks for investigating.

**Comment by IanLunn** [comment]
Thank you. If you have further issues, please let me know and I'll reopen
