### ISSUE TITLE
require('hover.css');

### ISSUE THREAD

**Issue by luqingxuan** [IanLunn/Hover#94]
when i require this , error always happen, why named it hover.css, but not hovercss or anything else?
install cmd:npm install hover.css --save-dev
i don't know how to require it in *.js file
i know pure.css named purecss for example
and animate.css named animate.css,it works

**Comment by Phillip2025** [comment]
this works for me:

require('hover.css/css/hover.css');

**Comment by IanLunn** [comment]
Thanks @Phillip2025
