### ISSUE TITLE
@mixin float

### ISSUE THREAD

**Issue by skynet** [IanLunn/Hover#96]
No idea what's the point for doing:

```
  -webkit-transform: translateX(-8px);
  transform: translateX(-8px);
```

This makes my images jump.

**Comment by IanLunn** [comment]
It causes the element to animate into place once before the looped float animation starts. There isn't a jump on the demo page so I expect you have additional CSS cancelling the transition on the element. Closing but if still an issue, please provide a link showing the issue.
