### ISSUE TITLE
disappear and show up issue on internet explorer 

### ISSUE THREAD

**Issue by tmrdurgun** [IanLunn/Hover#97]
When hover, element first disappear for 1 sec and then animating :/

**Comment by ylashin** [comment]
Seems like **transform : ScaleZ(0)** which comes from **hvr-grow** causes this issue.
I added the below to my app stylesheet and it works fine now

```
.hvr-grow {  
 -webkit-transform: none;
  transform: none;  
}
```

**Comment by IanLunn** [comment]
See https://github.com/IanLunn/Hover/issues/71
